branch-defaults:
  default:
    environment: study-sync-000-eb-dev
    group_suffix: null
  master:
    environment: study-sync-000-eb-dev
    group_suffix: null
global:
  application_name: study-sync-000-eb
  branch: null
  default_ec2_keyname: null
  default_platform: Docker running on 64bit Amazon Linux 2023
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: StudySync-000
  sc: git
  workspace_type: Application
